-- ==============================================================
-- File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
-- Version: 2013.4
-- Copyright (C) 2013 Xilinx Inc. All rights reserved.
-- 
-- ==============================================================

library ieee; 
use ieee.std_logic_1164.all; 
use ieee.std_logic_unsigned.all;

entity huffman_decoder_val_table_rom is 
    generic(
             dwidth     : integer := 6; 
             awidth     : integer := 6; 
             mem_size    : integer := 64
    ); 
    port (
          addr0      : in std_logic_vector(awidth-1 downto 0); 
          ce0       : in std_logic; 
          q0         : out std_logic_vector(dwidth-1 downto 0);
          clk       : in std_logic
    ); 
end entity; 


architecture rtl of huffman_decoder_val_table_rom is 

signal addr0_tmp : std_logic_vector(awidth-1 downto 0); 
type mem_array is array (0 to mem_size-1) of std_logic_vector (dwidth-1 downto 0); 
signal mem : mem_array := (
    0 => "000000", 1 => "000100", 2 => "010000", 3 => "010100", 4 => "000001", 
    5 => "000010", 6 => "000101", 7 => "000110", 8 => "001000", 9 => "010001", 
    10 => "010010", 11 => "010101", 12 => "010110", 13 => "011000", 14 => "100000", 
    15 => "100100", 16 => "000011", 17 => "000111", 18 => "001001", 19 => "001010", 
    20 => "010011", 21 => "010111", 22 => "011001", 23 => "011010", 24 => "100001", 
    25 => "100010", 26 => "100101", 27 => "100110", 28 => "101000", 29 => "001011", 
    30 => "001100", 31 => "011011", 32 => "011100", 33 => "100011", 34 => "100111", 
    35 => "101010", 36 => "110000", 37 => "110100", 38 => "101001", 39 => "001101", 
    40 => "011101", 41 => "011110", 42 => "110001", 43 => "110010", 44 => "110101", 
    45 => "110110", 46 => "001110", 47 => "101011", 48 => "101100", 49 => "111000", 
    50 => "001111", 51 => "011111", 52 => "101101", 53 => "101110", 54 => "110011", 
    55 => "110111", 56 => "111001", 57 => "111010", 58 => "101111", 59 => "111011", 
    60 => "111100", 61 => "111101", 62 => "111110", 63 => "111111" );


attribute EQUIVALENT_REGISTER_REMOVAL : string;
begin 


memory_access_guard_0: process (addr0) 
begin
      addr0_tmp <= addr0;
--synthesis translate_off
      if (CONV_INTEGER(addr0) > mem_size-1) then
           addr0_tmp <= (others => '0');
      else 
           addr0_tmp <= addr0;
      end if;
--synthesis translate_on
end process;

p_rom_access: process (clk)  
begin 
    if (clk'event and clk = '1') then
        if (ce0 = '1') then 
            q0 <= mem(CONV_INTEGER(addr0_tmp)); 
        end if;
    end if;
end process;

end rtl;


Library IEEE;
use IEEE.std_logic_1164.all;

entity huffman_decoder_val_table is
    generic (
        DataWidth : INTEGER := 6;
        AddressRange : INTEGER := 64;
        AddressWidth : INTEGER := 6);
    port (
        reset : IN STD_LOGIC;
        clk : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR(AddressWidth - 1 DOWNTO 0);
        ce0 : IN STD_LOGIC;
        q0 : OUT STD_LOGIC_VECTOR(DataWidth - 1 DOWNTO 0));
end entity;

architecture arch of huffman_decoder_val_table is
    component huffman_decoder_val_table_rom is
        port (
            clk : IN STD_LOGIC;
            addr0 : IN STD_LOGIC_VECTOR;
            ce0 : IN STD_LOGIC;
            q0 : OUT STD_LOGIC_VECTOR);
    end component;




begin
    huffman_decoder_val_table_rom_U :  component huffman_decoder_val_table_rom
    port map (
        clk => clk,
        addr0 => address0,
        ce0 => ce0,
        q0 => q0);

end architecture;


