onerror {resume}
quietly WaveActivateNextPane {} 0
add wave -noupdate /uniform_sampler_tb/clk
add wave -noupdate /uniform_sampler_tb/enable_s1
add wave -noupdate /uniform_sampler_tb/enable_s2
add wave -noupdate /uniform_sampler_tb/reset
add wave -noupdate /uniform_sampler_tb/seed
add wave -noupdate /uniform_sampler_tb/key
add wave -noupdate /uniform_sampler_tb/ready
add wave -noupdate /uniform_sampler_tb/s1_out
add wave -noupdate /uniform_sampler_tb/s1_addr
add wave -noupdate /uniform_sampler_tb/s1_valid
add wave -noupdate /uniform_sampler_tb/s2_out
add wave -noupdate /uniform_sampler_tb/s2_addr
add wave -noupdate /uniform_sampler_tb/s2_valid
add wave -noupdate -divider {Uniform Sampler}
add wave -noupdate /uniform_sampler_tb/uut/clk
add wave -noupdate /uniform_sampler_tb/uut/ready
add wave -noupdate /uniform_sampler_tb/uut/enable_s1
add wave -noupdate /uniform_sampler_tb/uut/enable_s2
add wave -noupdate /uniform_sampler_tb/uut/reset
add wave -noupdate /uniform_sampler_tb/uut/seed
add wave -noupdate /uniform_sampler_tb/uut/key
add wave -noupdate /uniform_sampler_tb/uut/s1_out
add wave -noupdate /uniform_sampler_tb/uut/s1_addr
add wave -noupdate /uniform_sampler_tb/uut/s1_valid
add wave -noupdate /uniform_sampler_tb/uut/s2_out
add wave -noupdate /uniform_sampler_tb/uut/s2_addr
add wave -noupdate /uniform_sampler_tb/uut/s2_valid
add wave -noupdate /uniform_sampler_tb/uut/s1_clk_en
add wave -noupdate /uniform_sampler_tb/uut/s1_rst
add wave -noupdate /uniform_sampler_tb/uut/s1_buf_empty
add wave -noupdate /uniform_sampler_tb/uut/s1_din_refresh
add wave -noupdate /uniform_sampler_tb/uut/s1_valid_out
add wave -noupdate /uniform_sampler_tb/uut/s1_valid_sampler
add wave -noupdate /uniform_sampler_tb/uut/s2_clk_en
add wave -noupdate /uniform_sampler_tb/uut/s2_rst
add wave -noupdate /uniform_sampler_tb/uut/s2_buf_empty
add wave -noupdate /uniform_sampler_tb/uut/s2_din_refresh
add wave -noupdate /uniform_sampler_tb/uut/s2_valid_out
add wave -noupdate /uniform_sampler_tb/uut/s2_valid_sampler
add wave -noupdate /uniform_sampler_tb/uut/aes_rst
add wave -noupdate /uniform_sampler_tb/uut/aes_enable
add wave -noupdate /uniform_sampler_tb/uut/aes_dout
add wave -noupdate /uniform_sampler_tb/uut/aes_done
add wave -noupdate /uniform_sampler_tb/uut/fifo_srst
add wave -noupdate /uniform_sampler_tb/uut/fifo_din
add wave -noupdate /uniform_sampler_tb/uut/fifo_rd_en
add wave -noupdate /uniform_sampler_tb/uut/fifo_dout
add wave -noupdate /uniform_sampler_tb/uut/fifo_full
add wave -noupdate /uniform_sampler_tb/uut/fifo_almost_full
add wave -noupdate /uniform_sampler_tb/uut/fifo_empty
add wave -noupdate /uniform_sampler_tb/uut/fifo_almost_empty
add wave -noupdate /uniform_sampler_tb/uut/fifo_valid
add wave -noupdate /uniform_sampler_tb/uut/fifo_data_count
add wave -noupdate /uniform_sampler_tb/uut/state_reg
add wave -noupdate /uniform_sampler_tb/uut/enable_s1_intern
add wave -noupdate /uniform_sampler_tb/uut/enable_s2_intern
add wave -noupdate /uniform_sampler_tb/uut/finished_output
add wave -noupdate /uniform_sampler_tb/uut/processing_fifo
add wave -noupdate /uniform_sampler_tb/uut/counter
add wave -noupdate -divider S!
add wave -noupdate /uniform_sampler_tb/uut/S1/clk
add wave -noupdate /uniform_sampler_tb/uut/S1/clk_en
add wave -noupdate /uniform_sampler_tb/uut/S1/rst
add wave -noupdate /uniform_sampler_tb/uut/S1/buf_empty
add wave -noupdate /uniform_sampler_tb/uut/S1/din_refresh
add wave -noupdate /uniform_sampler_tb/uut/S1/din
add wave -noupdate /uniform_sampler_tb/uut/S1/dout
add wave -noupdate /uniform_sampler_tb/uut/S1/valid
add wave -noupdate /uniform_sampler_tb/uut/S1/dout_r1
add wave -noupdate /uniform_sampler_tb/uut/S1/valid_r1
add wave -noupdate /uniform_sampler_tb/uut/S1/din_refresh_r1
add wave -noupdate /uniform_sampler_tb/uut/S1/din_r1
add wave -noupdate /uniform_sampler_tb/uut/S1/counter
add wave -noupdate /uniform_sampler_tb/uut/S1/SAMPLE_WIDTH
add wave -noupdate /uniform_sampler_tb/uut/S1/SAMPLES_PER_BLOCK
add wave -noupdate /uniform_sampler_tb/uut/S1/S_MAX
TreeUpdate [SetDefaultTree]
WaveRestoreCursors {{Cursor 1} {4850657 ps} 0}
configure wave -namecolwidth 277
configure wave -valuecolwidth 100
configure wave -justifyvalue left
configure wave -signalnamewidth 0
configure wave -snapdistance 10
configure wave -datasetprefix 0
configure wave -rowmargin 4
configure wave -childrowmargin 2
configure wave -gridoffset 0
configure wave -gridperiod 1
configure wave -griddelta 40
configure wave -timeline 0
configure wave -timelineunits ns
update
WaveRestoreZoom {0 ps} {23615639 ps}
